app = "bajaj-finserv-assingment-backend"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"
  build-target = "final"

[env]
  PYTHONUNBUFFERED = "1"
  UVICORN_HOST = "0.0.0.0"
  UVICORN_PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[checks.healthcheck]
  type = "http"
  port = 8080
  path = "/"
  interval = "30s"
  timeout = "5s"
